### PR TITLE
Add audio-playback plug

### PR DESCRIPTION
**Pull request by lucyllewy**
Signed-off-by: Daniel Llewellyn <daniel@bowlhat.net>

### CODE REVIEW

**Comment by popey** [comment]
Some thoughts on this. 
1) What happens if you're not on snapd 2.41 and use this interface? Does it just not connect to anything, and pulseaudio continues to work or is there an error?
2) We should move this to core18
3) Because then we could standardize on the travis config and --use-lxd ;)

**Comment by lucyllewy** [comment]
I believe it ignores interfaces that it doesn't know about so `audio-playback` will just remain unconnected. @jdstrand might be able to advise better - this is the suggested migration path: add `audio-*` plugs in addition to `pulseaudio`; the latter will be grandparented by the store for now; when snapd no-longer supports `pulseaudio` drop it from the list.

https://forum.snapcraft.io/t/upcoming-pulseaudio-interface-deprecation/13418

**Comment by jdstrand** [comment]
> I believe it ignores interfaces that it doesn't know about so `audio-playback` will just remain unconnected. @jdstrand might be able to advise better - this is the suggested migration path: add `audio-*` plugs in addition to `pulseaudio`; the latter will be grandparented by the store for now; when snapd no-longer supports `pulseaudio` drop it from the list.

In general yes. It is fine to add the interface ahead of time. The store knows about it so reviews won't fail and snapd <2.40 will just ignore it. Pulseaudio will continue to be auto-connected in 2.41 and earlier. At some point, possibly 2.42, pulseaudio will move to manually connected, but existing snaps will be grandfathered in. In this manner and in all cases it is fine to specify both forever. 

It would be ok for new snaps to still plugs pulseaudio since it won't be auto-connected, but once 2.41 is everywhere, I plan to adjust the snapcraft-desktop-helpers, etc to no longer add pulseaudio by default for cleanliness reasons.

**Comment by lucyllewy** [comment]
@popey are you happy to merge this? (I **do** have permission on this particular repo to do so myself)

**Pull request merged**
